services:
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared-net
    command: redis-server --appendonly yes

  gateway:
    platform: linux/amd64
    build:
      context: ../../microservices/gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - shared-net

volumes:
  redis_data:

networks:
  shared-net:
    external: true
