services:
  shop-db:
    platform: linux/amd64
    image: postgres:17
    restart: always
    env_file:
      - shop.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    networks:
      - shared-net

  shop-service:
    platform: linux/amd64
    image: crodion/shop-service:latest
    restart: always
    env_file:
      - shop.env
    ports:
      - "6001-6002:${PORT}"
    environment:
      SERVICE_ROUTE: /api/shop
      GATEWAY_URL: http://gateway:3000
    depends_on:
      - shop-db
    networks:
      - shared-net
    deploy:
      replicas: 2

volumes:
  shop-db-data:

networks:
  shared-net:
    external: true
