services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_game:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  game-service:
    image: edyson1202/game-service:1.0
    restart: always
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
volumes:
  pgdata_game: