services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXPOSE}:5432"
    networks:
      - roleplay-network

  roleplay-service:
    image: crodion/roleplay-service:1.0.1
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER_DOCKER}
      - DB_PASSWORD=${DB_PASSWORD_DOCKER}
      - DB_HOST=${DB_HOST_DOCKER}
      - DB_PORT=${DB_PORT_DOCKER}
      - DB_NAME=${DB_NAME_DOCKER}
    depends_on:
      - db
    networks:
      - roleplay-network

volumes:
  postgres_data:

networks:
  roleplay-network:
    driver: bridge
