services:
  roleplay-db:
    image: postgres:17
    restart: always
    env_file:
      - roleplay.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - roleplay-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    networks:
      - roleplay-network
      - shared-net

  roleplay-service:
    image: crodion/roleplay-service:latest
    env_file:
      - roleplay.env
    environment:
      SERVICE_NAME: roleplay-service
      SERVICE_PORT: 8200
      SERVICE_ROUTE: /api/roleplay
      BROKER_URL: http://message-broker:4000
    depends_on:
      - roleplay-db
    deploy:
      replicas: 3
    networks:
      - roleplay-network
      - shared-net

volumes:
  roleplay-db-data:

networks:
  roleplay-network:
    driver: bridge
  shared-net:
    external: true
