services:
  roleplay-db:
    platform: linux/amd64
    image: postgres:17
    restart: always
    env_file:
      - roleplay.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - roleplay-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    networks:
      - roleplay-network
      - shared-net

  roleplay-service-1:
    platform: linux/amd64
    image: crodion/roleplay-service:latest
    container_name: roleplay-service-1
    ports:
      - "8201:8200"
    env_file:
      - roleplay.env
    environment:
      - SERVICE_NAME=roleplay-service-1
      - SERVICE_PORT=8200
      - SERVICE_ROUTE=/api/roleplay
      - GATEWAY_URL=http://gateway:3000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - roleplay-db
    networks:
      - roleplay-network
      - shared-net

  roleplay-service-2:
    platform: linux/amd64
    image: crodion/roleplay-service:latest
    container_name: roleplay-service-2
    ports:
      - "8202:8200"
    env_file:
      - roleplay.env
    environment:
      - SERVICE_NAME=roleplay-service-2
      - SERVICE_PORT=8200
      - SERVICE_ROUTE=/api/roleplay
      - GATEWAY_URL=http://gateway:3000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - roleplay-db
    networks:
      - roleplay-network
      - shared-net

  roleplay-service-3:
    platform: linux/amd64
    image: crodion/roleplay-service:latest
    container_name: roleplay-service-3
    ports:
      - "8203:8200"
    env_file:
      - roleplay.env
    environment:
      - SERVICE_NAME=roleplay-service-3
      - SERVICE_PORT=8200
      - SERVICE_ROUTE=/api/roleplay
      - GATEWAY_URL=http://gateway:3000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - roleplay-db
    networks:
      - roleplay-network
      - shared-net

volumes:
  roleplay-db-data:

networks:
  roleplay-network:
    driver: bridge
  shared-net:
    external: true
