services:
  game-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-game_db}
    volumes:
      - pgdata_game:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    networks:
      - shared-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  game-service:
    image: edyson1202/game-service:2.0
    restart: always
    environment:
      POSTGRES_HOST: game-db
      POSTGRES_PORT: 5432
      GATEWAY_URL: http://gateway:3000
    env_file:
      - game.env
    ports:
      - "4141-4143:${PORT}"
    depends_on:
      game-db:
        condition: service_healthy
    networks:
      - shared-net
    deploy:
      replicas: 3
      
volumes:
  pgdata_game:

networks:
  shared-net:
    external: true
